### ISSUE TITLE
CollectionPerformerObj.save(event) for onEventLoading event

### ISSUE THREAD

**Issue by nabiltntn** [DHTMLX/meteor-scheduler-data#10]
Why is this block useful since we already loading the event, why we should make a save ?

``` js

gEventsCollection.add(this.attachEvent("onEventLoading", function(event) {
        CollectionPerformerObj.save(event);
        return true;
    }));
```

**Comment by saltomodules** [comment]
I'm also very curious what the use of this block of code is. 

All these collection updates cause a very serious performance hit when loading the planner with larger collections.

With the `CollectionPerformerObj.save(event); ` line commented out load times decrease eighty percent and it doesn't seem to affect the functioning of the planner at all.

**Comment by mperednya** [comment]
onEventLoading handler was removed.
