### ISSUE TITLE
ReferenceError: scheduler is not defined

### ISSUE THREAD

**Issue by ymboda** [DHTMLX/meteor-scheduler-data#3]
Hello,

I have followed the read me but I'm always having the same error "ReferenceError: scheduler is not defined".

Can you add an example of using this package, please ?
Thanks

**Comment by EgorLazarovich** [comment]
Hello! Please, look at this https://github.com/DHTMLX/meteor-examples.

**Comment by ymboda** [comment]
Hello,

Many thanks.

Do you have an example with recurring events, please ?

Regards

**Comment by EgorLazarovich** [comment]
For working recurring events, just add js file with this extension to folder "[your app folder]/client/compatibility"

**Comment by ymboda** [comment]
Perfect.

It works.

Many thanks.

**Comment by EgorLazarovich** [comment]
You are welcome! :)

**Comment by ymboda** [comment]
Hi,

May I ask you one more question, please ?

I’m trying to customize the form with :
- 3 more fields : 2 text fields (one selectable) and 1 numeric
- giving the possibility to schedule an event more than once a day using the same form, for example repeat the event « X » daily, at 8:00, 12:00 and 18:00, during 6 months

Can you guide me, please ?

I have tried, but whenever I customize the form, I loose the recurring event possibility.

Many thanks.

**Comment by pvtulsiram538** [comment]
Hi i have also done the same process and i have created folder client/compatibilty/ and i have placed meteor example.js file at there. un fortunately not working for me

**Comment by pvtulsiram538** [comment]
HI which extension i need to add in specified folder  by you  

thanks

**Comment by aquinoti** [comment]
Hi, I have the same error "ReferenceError: scheduler is not defined", but in Meteor 1.4.2.7 version. Since the directories' structure was changed and I had rewrote the code and i'm completelly lost.
